### ISSUE TITLE
Error when searching without item_type

### ISSUE THREAD

**Issue by breakthestatic** [fondberg/spotcast#494] opened 2024-12-04 22:19 UTC
### The problem

In v3.8, the general, type-agnostic search was replaced by type-specific searches only, which although offering additional specificity in *certain* use-cases, presented a general regression for users looking to simply search for a term across all types (relying on Spotify's internal ranking logic).

With the major re-write, and the lack of any `required` flag on the `item_type` argument, I was hoping that this regression would be rectified. However, as of the b14, I'm still not able to perform general searches. When omitting the `item_type`, the services fails with the following error:

```
Failed to perform the action spotcast.play_from_search. required key not provided @ data['item_type']. Got None
```

I'm not well versed in Python, but found some schema code in play_from_search.py, indicating that the field is actually required currently. Is there any reason why this can't be an optional list instead of a single, required type? It likely doesn't matter if the functionality is opt-in or opt-out, but the ability to search across several types at once should at least be offered.

Providing a list of types would allow a variety of use-cases. Users who want granularity can still select the single type they want, and users who want to let Spotify handle result disambiguation can select multiple types. Looking at the Spotify API itself, it looks to be just a comma-delimited query param. Once again, not a Python dev, but I can't imagine that's very hard to implement.

## System Information

version | core-2024.12.0
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | homeassistant
virtualenv | true
python_version | 3.13.0
os_name | Linux
os_version | 6.1.0-28-amd64
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4987
Installed Version | 2.0.1
Stage | running
Available Repositories | 1475
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 19
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 2, 2024 at 6:53 PM
-- | --
current_recorder_run | December 4, 2024 at 1:33 PM
estimated_db_size | 539.06 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotcast</summary>

Version | 5.0.0-b14
-- | --
Breakthestatic Is Default | true
Breakthestatic Public Endpoint | ok
Breakthestatic Public Token | failed to load: unhealthy
Breakthestatic Private Endpoint | ok
Breakthestatic Private Token | healthy

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### What type of installation are you running?

Home Assistant Container

**Comment by fcusson** [comment] 2024-12-04 23:59
@breakthestatic Moving to enhancement since the current behaviour is the expected behavior in the beta

> Looking at the Spotify API itself, it looks to be just a comma-delimited query param. Once again, not a Python dev, but I can't imagine that's very hard to implement.

That is the very easy part. The complex part is in deciding what to provide to the user based on the result.

Let's say that when requesting a search result we receive some tracks some albums and some artist as well as an audiobook. What should be picked? What decision algorithm should be put in place?

That's where the complexity lies. Different people might have different interpretation of what would be the best decision.

Personally, I wanted to check if someone would miss it during the beta, so thanks for feedback. Now let's have a discussion on the implementation.

How should we make a decision between the multiple types in your opinion?

**Comment by breakthestatic** [comment] 2024-12-05 17:21
Ah, I think I misunderstood one of Spotify's response parameters - `popularity`. Initially, I thought that field was essentially a relevance score and could be used to determine the "top" pick. However, on a a re-reading, I see that it truly is a *popularity* score based loosely on how many people are interacting with that piece of content, and likely isn't *very* useful for our intended ranking across types.

Your proposal makes sense to me. One additional idea I had was to possibly use the *order* of the types in the list for weighting and/or tie-breaking. E.g. if the list is `['album', 'track', 'artist']`, searching for "Metallica" would return their self-titled album over the band itself. I'm not sure if the Home Assistant UI has a draggable chip type of component which could be used to handle the ordering from the UI though.

**Comment by fcusson** [comment] 2024-12-05 17:59
> I'm not sure if the Home Assistant UI has a draggable chip type of component which could be used to handle the ordering from the UI though.

Not to my knowledge, but this could be an additional key in data to provide a custom ordering as a list. I would still want a multi-select for the items, so that the user has a visual queue of what the search does. Also, I won't allow a no item-type, but I will put a default value. For me what made the most sense would be to select by default `artist`, `album`, `track`, `playlist`. That way it is specifically a music search by default and needs modification to the service call to get a different behavior.

**Comment by fcusson** [comment] 2024-12-10 18:51
build 16 released with multi type search. Closing the ticket. Ability to change priority order will come later

**Closed by fcusson** 2024-12-10 18:51 UTC
Labels: enhancement, beta

**Comment by breakthestatic** [comment] 2024-12-11 17:03
The multi-type search works well so far from my testing; all misses (results different than what i intended) were for very ambiguous queries that I wouldn't even expect Google, Alexa, etc. to get right without any context (e.g. a prior preference for playing the intended item).  On the b16 release I am seeing a larger number of log errors (some related to logging the `play_from_search` call. I'll create new issue(s) as necessary.
