### ISSUE TITLE
Spotcast not working after newest update

### ISSUE THREAD

**Issue by Ky0sHiR00** [fondberg/spotcast#405] opened 2023-09-06 12:38 UTC
# Bug Ticket

## Describe the bug

<A clear and concise description of what the bug is.>

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ ] Using latest version of spotcast **yes**
* [ ] Using latest stable version of Home Assistant **yes**
* [ ] I have setup the Spotify integration in Home Assistant **yes**
* [ ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log)) **yes**
* [ ] (optional) I have Spotify Premium **yes**
* [ ] (optional) I am using multiple accounts **no**
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log)) **yes**
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains **yes**

## Environment

 - Installation type: [HA_OS|Container|Supervised|Core] **core**
 - HA version: [ ] **core-2023.8.4**
 - spotcast version: [ ] **newest**

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
alias: Play Spotify Favorites
sequence:
  - service: spotcast.start
    continue_on_error: true
    data:
      random_song: true
      shuffle: true
      start_volume: 60
      uri: spotify:playlist:4G465m8EaeGUuzvoahWKVj
      entity_id: media_player.lazienka
mode: single
icon: mdi:music

````

## Logs

* normal|debug

````log
`Exception caught while sending message to controller SpotifyController: Message urn:x-cast:com.spotify.chromecast.secure.v1 from 9af786d8-90d0-44a3-8260-150528b31b07 to sender-0: {'type': 'getInfoResponse', 'payload': {'version': '2.9.0', 'publicKey': 'empty', 'remoteName': 'Spotify on Cast', 'deviceType': 'cast_audio', 'brandDisplayName': 'google', 'modelDisplayName': 'Google_Home', 'libraryVersion': '5.30.3', 'resolverVersion': '1', 'groupStatus': 'NONE', 'deviceAPI_isGroup': False, 'tokenType': 'accesstoken', 'clientID': 'xxx', 'productID': 0, 'scope': 'streaming', 'availability': '', 'spotifyError': 0, 'status': 101, 'statusString': 'OK'}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pychromecast/socket_client.py", line 719, in _route_message
    handled = handler.receive_message(message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotify_controller.py", line 47, in receive_message
    self.device = data["payload"]["deviceID"]
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'deviceID'`

============


Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.11/site-packages/pychromecast/socket_client.py:398
First occurred: 5 września 2023 10:00:49 (44 occurrences)
Last logged: 13:37:41

[(192.168.xx.xx):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.31.7', 8009)), retrying in 5.0s
[Glosnik Salon(192.168.xx.xx):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.31.173', 8009)), retrying in 5.0s
[Łazienka(192.168.xx.xx):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.31.7', 8009)), retrying in 5.0s
[Google Hub(192.168.xx.xx):8009] Failed to connect to service ServiceInfo(type='mdns', data='google-nest-hub-6d50de5482ea609d3fc3cfe1f08f94c9._googlecast._tcp.local.'), retrying in 5.0s
````

## Additional context

<Add any other context about the problem here.>

**Comment by fcusson** [comment] 2023-09-06 22:30
Duplicate of #398

**Closed** 2023-09-06 22:30 UTC
Labels: bug
