### ISSUE TITLE
Timeout when waiting for status response from Spotify app

### ISSUE THREAD

**Issue by johannwilken** [fondberg/spotcast#400] opened 2023-08-31 16:40 UTC
# Bug Ticket

## Describe the bug

For the last few days Spotcast is not working anymore. Multiple accounts not working.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [y] Using latest version of spotcast
* [y ] Using latest stable version of Home Assistant
* [y ] I have setup the Spotify integration in Home Assistant
* [y ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [y ] (optional) I have Spotify Premium
* [y ] (optional) I am using multiple accounts
* [ y] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ y] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [ 2023.8.4]
 - spotcast version: [3.7.0 ]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
  sp_dc: !secret jw_sp_dc
  sp_key: !secret jw_sp_key
  accounts:
   johann:
    sp_dc: !secret jw_sp_dc
    sp_key: !secret jw_sp_key
   elandi:
    sp_dc: !secret ew_sp_dc
    sp_key: !secret ew_sp_key

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
service: spotcast.start
data:
  entity_id: media_player.master_bedroom_speaker
  uri: spotify:playlist:$#$#$#$#$#$#$#$#
  account: johann
  random_song: true
  shuffle: true
  ignore_fully_played: true
continue_on_error: true
````

## Logs

* normal|debug

````log 1
<Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/spotify_controller.py:104
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:25:30 PM (2 occurrences)
Last logged: 6:28:01 PM

[140520622190912] Timeout when waiting for status response from Spotify app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 607, in _service_handler
    response = await self._async_start_run(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 566, in _async_start_run
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 596, in _async_run
    return await self.script.async_run(script_vars, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1569, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 516, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2018, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/__init__.py", line 221, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 250, in get_spotify_device_id
    spotify_cast_device.startSpotifyController(access_token, expires)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 95, in startSpotifyController
    sp.launch_app()
  File "/config/custom_components/spotcast/spotify_controller.py", line 104, in launch_app
    raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
>
````

## Additional context

<Add any other context about the problem here.>

**Comment by antonio1475** [comment] 2023-09-01 07:35
Duplicate of https://github.com/fondberg/spotcast/issues/398 ?

**Closed** 2023-09-01 09:54 UTC
Labels: bug
