### ISSUE TITLE
Got the error _http status: 404 [...] Device not found, reason: None_ when trying to call the service to a Spotify Connect device.

### ISSUE THREAD

**Issue by Luth1ng** [fondberg/spotcast#264] opened 2021-11-06 04:05 UTC
* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains
* [x] I'm using spotify_device_id but the issue remains

**Describe the bug**
Got the error _http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=bc89e722-bb6d-4446-bc9f-3b2f3a265895: Device not found, reason: None_ when trying to call the service to a Spotify Connect device.

**Environment (please complete the following information):**
 - HA version: [core-2021.11.1]
 - spotcast version: [v3.6.21]

**Configuration**

     - icon: mdi:television
        type: service
        id: spotcast.start
        data:
          uri: spotify:playlist:37i9dQZF1DXdrln2UyZD7F
          random_song: true
          shuffle: true
          start_volume: 50
          spotify_device_id: bc89e722-bb6d-4446-bc9f-3b2f3a265895

**Additional context**
The device is available within the legacy Spotify app.
I looked in the Dev Spotify Console [https://developer.spotify.com/console/get-users-available-devices/](url), it seems that the api doesn't retrieve my device - is this the same for Spotcast ?
After enabled the device through the  the legacy Spotify app, this Spotcast service is running fine, and the Spotify api is able to retrieve the device.

**Debug logs**

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/spotcast_controller.py:272
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:39:39 (5 occurrences)
Last logged: 07:50:42
[139838482340016] http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=bc89e722-bb6d-4446-bc9f-3b2f3a265895: Device not found, reason: None

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/play?device_id=bc89e722-bb6d-4446-bc9f-3b2f3a265895

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1534, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 176, in start_casting
    spotcast_controller.play(
  File "/config/custom_components/spotcast/spotcast_controller.py", line 272, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 1761, in start_playback
    return self._put(
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 306, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=bc89e722-bb6d-4446-bc9f-3b2f3a265895:
 Device not found, reason: None
```

**Comment by Darkfull-Dante** [comment] 2021-11-06 13:02
There seem to be a problem in the api call toward Spotify id at the moment. I'll look into it. I add the same traceback when using the uuid. You can circumvent the situation by calling the entity_id instead. This didn't come up during testing for 3.6.21.

For future reference, it is not a duplicate of #261, this 404 error is related to player id api call not playlist api call

**Comment by Darkfull-Dante** [comment] 2021-11-06 13:03
@Luth1ng, can you confirm the usage of entity_id instead of spotify_id works for you?

**Comment by Luth1ng** [comment] 2021-11-06 14:21
Hi @Darkfull-Dante 

I cannot use the entity_id as it's not an entity added to my home assistant instance. It's just a regular device (TV) with the Spotify Connect capability. It's the same for my PS5 for example.

Well, I followed the instructions from the README, and got the ID in logs : 
`2021-11-06 18:07:25 DEBUG (SyncWorker_4) [custom_components.spotcast.helpers] get_spotify_devices: media_player.spotify_jeremy_girault: Spotify Jeremy Girault: [{'id': '1cf6ee527e4a343d412ef151200fa71afc77c99c', 'is_active': False, 'is_private_session': False, 'is_restricted': False, 'name': 'DESKTOP-4AKPLC2', 'type': 'Computer', 'volume_percent': 50}, {'id': 'bc89e722-bb6d-4446-bc9f-3b2f3a265895', 'is_active': True, 'is_private_session': False, 'is_restricted': False, 'name': '[LG] webOS TV OLED55B8PLA', 'type': 'TV', 'volume_percent': 100}]`

What is strange is the "get_spotify_devices" service cannot get all my Spotify Connect devices until I enabled manually with the legacy Spotify App.

Here are some attached screenshots of the process :
- 2021-11-06 18_16_13 - Home Assistant.png : Only one device is listed...
- 2021-11-06 18_16_43-Spotify.png : ...whereas Spotify can list other devices
- 2021-11-06 18_17_20-Spotify.png : And when I enable this one for example...
- 2021-11-06 18_17_37 - Home Assistant.png : It gets available through Spotcast

Many thanks for understanding

**Comment by Darkfull-Dante** [comment] 2021-11-06 14:31
Thank you for the detail @Luth1ng. What is strange is that the ID contains '-' which shouldn't be the case for a device ID. I'm unfamiliar with webOS devices are they chromecast base for the spotify play back or do they have their own backend?

**Comment by Luth1ng** [comment] 2021-11-06 18:36
It’s their own backend like the PS5 is a native app on the OS. It’s very similar to chromecast casting. 

Just the Windows Spotify software. It also works with iOS app or web app (open.spotify.com)

**Comment by Darkfull-Dante** [comment] 2021-11-06 20:12
@Luth1ng When you check in the dev tool your media_player entity linked to your spotify account can you see the webos tv in the source_list?

**Comment by Luth1ng** [comment] 2021-11-06 21:08
> 
> 
> @Luth1ng When you check in the dev tool your media_player entity linked to your spotify account can you see the webos tv in the source_list?

No, here's my config :

`source_list:
  - DESKTOP-4AKPLC2
volume_level: 0
media_content_type: music
shuffle: false
friendly_name: Spotify
icon: mdi:spotify
supported_features: 444983
`

**Comment by Darkfull-Dante** [comment] 2021-11-06 21:41
Hi @Luth1ng, 

Well that's a problem, it's impossible for spot cast to communicate with a device if it's not in the spotify connect list. That list is fed directly from spotify so it is not dependant on your configuration of home assistant, spotify integration or spot cast.

Due to the fact, we are talking about a non Chromecast device, I will have to close the ticket. Spotcast is a layer to make spotify communicate with Chromecast devices that are set on your home assistant server. Your case is for a non Chromecast device that haven't been setup on your home assistant.

WebOS does have an integration for home assistant, I would suggest you look into setting that integration and looking into the spotify integration for transferring your playback. I do have to work toward that solution for my Xbox since it's not a Chromecast device I must use the spotify integration directly.

If you want pointers on setting that in home assistant I can help you, but Spotcast won't be able to help you in your case.

**Closed** 2021-11-07 02:01 UTC
Labels: bug

**Comment by dedors** [comment] 2021-12-10 13:54
Hi, I know it's closed, but I'm facing the same or similar problem when trying to play on a alexa echo dot.
The source list only shows my desktop, and starting playback on the echo fails (which also has a UUID style ID).
When I click the "connect to a device" icon on the desktop spotify app, the echo devices are first grayed out, but are available within a second. Without clicking on a device, the source list now shows all echo devices and playback with spotcast on the echo also works now.
After a short time after stopping playback, the echos will disapear in the source list again.

Is there a way to do a refresh for the connect devices with spotcast before sending the playlist?
