### ISSUE TITLE
Spotcast can't find Spotify integration even if it's installed

### ISSUE THREAD

**Issue by mfabiani53** [fondberg/spotcast#258] opened 2021-11-02 11:03 UTC
**Describe the bug**
After installing the latest release (v. 3.1.18) the integration is not loaded with the following errors:
```
2021-10-31 15:22:33 ERROR (SyncWorker_1) [custom_components.spotcast.helpers] spotify integration not found
2021-10-31 15:22:33 ERROR (SyncWorker_1) [custom_components.spotcast] Spotify integration was not found, aborting setup...
2021-10-31 15:22:33 ERROR (MainThread) [homeassistant.setup] Setup failed for spotcast: Integration failed to initialize.
2021-10-31 15:22:33 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform spotcast.sensor: Unable to set up component.
````
It seems spotcast is not recognizing the spotify integration regularly installed as you can see:

![image](https://user-images.githubusercontent.com/37701688/139834517-285b9874-853c-47c3-9997-4966de125ee5.png)

and also from /.storage/core_entity_registry it is completely loaded:
```
            {
                "entity_id": "media_player.spotify_mfabiani53",
                "config_entry_id": "xxxxxxxxxxxxxxxxxxxxxxx",
                "device_id": "xxxxxxxxxxxxxxxxxxxxx",
                "area_id": null,
                "unique_id": "mfabiani53",
                "platform": "spotify",
                "name": null,
                "icon": null,
                "disabled_by": null,
                "capabilities": {},
                "supported_features": 0,
                "device_class": null,
                "unit_of_measurement": null,
                "original_name": "Spotify mfabiani53",
                "original_icon": "mdi:spotify"
            },
```

When reverting back to the 3.1.17 release all is working ok !
I am trying to use the using latest version of spotcast v. 3.1.8
I am using latest stable version of Home Assistant

**Comment by snp88** [comment] 2021-11-03 08:30
Have the same issue 

Workaround is to completely restart your  virtual or real machine 
pull the plug ;)

**Comment by mfabiani53** [comment] 2021-11-03 10:53
@snp88 you mean i must turn off completely my raspberry and then turn on again?

**Comment by hmmbob** [comment] 2021-11-03 10:59
Possible regression of https://github.com/fondberg/spotcast/pull/255

@Darkfull-Dante

**Comment by snp88** [comment] 2021-11-03 11:11
@mfabiani53  i have my HA in virtual machine but in short word yes if you unplug your raspberry and turn on again it should be ok this is what i do with my HA but my instance is on Virtual machine

**Comment by Darkfull-Dante** [comment] 2021-11-03 11:24
thank you for the report @snp88, during testing I never add that race condition come up. We are releasing a new feature today from a PR we receive, we will simply keep the error message for the time being to be able to troubleshoot. I'll look into a more elegant way to test the presence of the Spotify integration

**Comment by Darkfull-Dante** [comment] 2021-11-03 11:39
I did a quick check of the manifest file and dev documentation and we could try and add spotify in the after_dependencies section of the manifest. For the current release I will go with simply the quick fix (not aborting the setup).

This potential solution still need testing before implementing

**Comment by Darkfull-Dante** [comment] 2021-11-03 11:53
#259 was merged with v3.6.19.

@hmmbob @snp88, I will keep this issue open for the moment, please report if the problem persists. I will work and test the after_dependencies solution. If I release a beta with the fix is any of you able to test under your setup? My current dev env only permits me to test the Docker install

**Comment by snp88** [comment] 2021-11-04 07:59
Hi 
@Darkfull-Dante  I update to newest spotcast and problem persist
but now beside errors spotcast work 

![image](https://user-images.githubusercontent.com/46537540/140277540-aa40239e-83b6-45b5-98df-c20413c7aee8.png)

**Comment by Darkfull-Dante** [comment] 2021-11-04 09:36
@snp88 it is normal, v3.6.19 only reverts the aborting of the setup for the moment, I still maintain the error log as a check, I'll be working on a beta release that contains the potential fix. I'm currently running that fix in my dev env without problem, sadly it doesn't mean much because I never had the race condition you had

**Comment by Darkfull-Dante** [comment] 2021-11-05 15:19
@snp88 can you confirm the issue with loading Spotcast integration is gone following v3.6.20? You should now have no error logs regarding finding the Spotify integration

**Comment by mfabiani53** [comment] 2021-11-05 19:33
On my system I still get errors in loading spotcast integration also with 3.1.20

custom_components.spotcast.helpers] spotify integration not found
2021-11-05 20:20:43 ERROR (SyncWorker_0) [custom_components.spotcast] Spotify integration was not found, please verify integration is functionnal. Could result in python error...

**Comment by Darkfull-Dante** [comment] 2021-11-05 20:21
@snp88 ok, thank you for the information, so even with forcing spotcast to load after spotify there is still a possible race condition for certain user. I'll remove the abort setup for following releases. Will simply keep it a debug log for the moment.

**Comment by mfabiani53** [comment] 2021-11-06 09:13
@Darkfull-Dante are you referring to my latest message?

**Comment by hmmbob** [comment] 2021-11-06 09:22
@mfabiani53 and @snp88: I wonder what will happen if you:

- disable spotcast (remove from configuration.yaml or put # in front of all spotcast related lines)
- delete the spotify integration, 
- restart HA
- add spotify again
- enable spotcast

As we only see 2 reports now (from you both), and Spotcast is used quite a bit, I am thinking it might be something locally. It's worth trying to see if it fixes the issue.

**Comment by Darkfull-Dante** [comment] 2021-11-06 13:04
oh sorry @mfabiani53, I referred to the wrong user, yes I was talking about your last message. Can you verify if the problem still persist in 3.6.21?

**Comment by mfabiani53** [comment] 2021-11-06 14:51
Yes asap I'll let you know...

**Comment by snp88** [comment] 2021-11-06 16:27
Hi All

sorry for late response 
since i update to the version .21 issue not show in my instance.
I trigger few restarts and no problem so in my opinion we are good to close this 
@Darkfull-Dante  thx for all work and fast reaction :)

**Comment by Darkfull-Dante** [comment] 2021-11-06 16:54
No problem, thank you for the testing. I'll keep this ticket around so we can eventually have an elegant way to test for the presence of the spotify integration

**Closed by Darkfull-Dante** 2021-11-06 16:54 UTC
Labels: bug
