### ISSUE TITLE
Unsuccessful token request, received code 302

### ISSUE THREAD

**Issue by ctankep23** [fondberg/spotcast#364] opened 2022-11-21 14:49 UTC
I am trying to set up Spotcast but no dice. In Dev tools I try:
```
service: spotcast.start
data: 
  device_name: media_player.kitchen_speaker
  uri: "spotify:playlist:37i9dQZF1DX3yvAYDslnv8"
  random_song: true
```
But I get a "Could not get Spotify Token" error. I've checked and refreshed and rechecked sp_dc and sp_keys. I've tried having them in the config.yaml and also in sercrets.yaml - no difference. I've tried with Spotify Device ID's and Device Name's - no difference. The Official Spotify Integration IS up and running..

Checking logs I see:

(On the top)
```
This error originated from a custom integration.

Logger: custom_components.spotcast.helpers
Source: custom_components/spotcast/helpers.py:61
Integration: Spotcast (documentation, issues)
First occurred: 15:29:31 (1 occurrences)
Last logged: 15:29:31

spotify integration not found
```
and below that in the actual logs:
```
2022-11-21 15:36:59.766 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=spotcast, service=start, service_data=device_name=media_player.kitchen_speaker, uri=spotify:playlist:37i9dQZF1DX3yvAYDslnv8, random_song=True>
2022-11-21 15:36:59.769 DEBUG (SyncWorker_2) [custom_components.spotcast.spotcast_controller] setting up with account default
2022-11-21 15:36:59.840 INFO (MainThread) [custom_components.spotcast.spotcast_controller] Unsuccessful token request, received code 302
```

* [x] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have Spotify Premium
* [x] I am using multiple accounts
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [x] I'm using entity_id in the service call and have tried device_name but the issue remains

## Configuration

Add your configuration

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

**Comment by hmmbob** [comment] 2022-11-21 15:13
The error is rather supportive:

> This error originated from a custom integration.
>
> Logger: custom_components.spotcast.helpers
> Source: custom_components/spotcast/helpers.py:61
> Integration: Spotcast (documentation, issues)
> First occurred: 15:29:31 (1 occurrences)
> Last logged: 15:29:31
> 
> **spotify integration not found**

^^ emphasis mine. Please install and setup spotify in HA first.

**Comment by ctankep23** [comment] 2022-11-21 15:38
Like I wrote:

”The Official Spotify Integration IS up and running..”

Im gonna remove both integrations and just try again.

**Comment by ctankep23** [comment] 2022-11-21 16:05
Reinstalled Spotify and set it up, callback URL working. Spotify Integration confirmed working.

Reinstalled Spotcast. Same thing. Using the Custom Spotify-card I can see what song is currently playing. On the top there is a warning saying "Spotcast integration has to be installed for this component to work".

And the original error message (Could not get Spotify Token) persists.

**Comment by dgarciadonado** [comment] 2022-11-27 10:47
Hello @ctankep23 I am experimenting the same issue. "could not get Spotify token"
 Spotify integration is correctly working. Have you been able to resolve it? Thank you

**Comment by ctankep23** [comment] 2022-11-27 13:29
> Hello @ctankep23 I am experimenting the same issue. "could not get Spotify token"
> Spotify integration is correctly working. Have you been able to resolve it? Thank you

Yes it has been resolved, as in I’m not getting any errors. I wish I could say what made it work in the end but it just started working after starting over for the fourth time. 

The whole incognito mode to get the keys is very finicky. They’re not uniform in length, one time you might get a shorter sp_dc and the next time it’s the sp_key which is long. And somehow my keys were updated right in the middle of the process.

Using device names works much better than spotcast IDs, as the devices seem to disappear when they’re not being used.

**Comment by techtim89** [comment] 2022-11-27 14:38
I too have been plagued with this issue.  It started Saturday morning "11/26" for me.  I have HASS installed in two separate locations and both are affected.  I've tried everything I can think of and have yet to resolve the issue.  On rare occasions it fires properly but never consistently.  I have Google audio devices and I've tried "Device Name" and "Entity ID" of the said Google devices.  It's definitely a SpotCast issue.

**Comment by fcusson** [comment] 2022-11-28 13:26
@techtim89, @ctankep23 @hmmbob wanted to validate if the problem was persisting. Erro 302 is a temporary redirect error. Meaning a URL is inaccessible at the time and another URL must be use, saddly, spotipy doesn't work well with redirect. I didn't have time to delve into the direct error, but a 302 is not an error on our hand. Since 302 is reserved for temporary problems, my guess would be this was due to changes in their backend.

Could I have a confirmation the service is backup?

**Comment by ctankep23** [comment] 2022-11-28 14:30
I just remembered something that might be important! -On a hunch I added multiple variations of the redirect url in Spotify developer.

http://<mylocalip>:8123/auth/external/callback

https://my.home-assistant.io/redirect/oauth

http://homeassistant.local:8123/auth/external/callback

http://homeassistant.local:8123/redirect/oauth

https://<mylocalip>:8123/redirect/oauth

https://my.home-assistant.io:8123/auth/external/callback

I think it started working after this.

**Comment by fcusson** [comment] 2023-03-07 13:05
Cleaning up older ticket. Please repoen if still present, but should be resolved with the new retries in `v3.7.0`.

**Closed by fcusson** 2023-03-07 13:05 UTC
Labels: bug

**Comment by Anon666333** [comment] 2023-09-23 03:26
Not sure how to reopen this...but I believe this is happening again.
Spotcast works properly on one of my accounts, but not the other. Have tried everything listed above here...and yes, the official Spotify integration is working properly for the problematic account through Spotcast...

**Comment by fcusson** [comment] 2023-09-23 13:48
@Anon666333, can you provide an error log so we can check if the problem is the same?

**Comment by Anon666333** [comment] 2023-09-23 13:58
@fcusson of course! Slightly different log entry, but same error of unable to get Spotify Token.
In this case, I'm trying to run the script from my phone, hence the second part of the log.

`2023-09-23 09:51:07.141 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Could not get spotify token.
2023-09-23 09:51:07.146 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [545941433152] Error handling message: Could not get spotify token. (unknown_error) redacted_name from reacted_ip_address (Mozilla/5.0 (Linux; Android 13; SM-S918W Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 Home Assistant/2023.9.2-11226 (Android 13; SM-redacted))

**Comment by fcusson** [comment] 2023-09-23 14:15
Do you have the http error code, if not you might have to enable debug log.

There can be a lot of reason why you couldn't get the token, in this tickets in particular, it turned out to be spotify moving a proxy server in the user's region.

**Comment by Anon666333** [comment] 2023-09-24 00:20
I think so... I turned on debug mode for Spotcast and this is the resulting log entry after attempting to start playback.

`2023-09-23 20:17:01.542 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2023-09-23 20:17:01.543 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2023-09-23 20:17:01.548 DEBUG (SyncWorker_5) [custom_components.spotcast.spotcast_controller] setting up with  account default
2023-09-23 20:17:01.845 INFO (MainThread) [custom_components.spotcast.spotcast_controller] Unsuccessful token request, received code 302
2023-09-23 20:17:01.849 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Could not get spotify token.
2023-09-23 20:17:01.855 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548178093120] Error handling message: Could not get spotify token. (unknown_error) Redacted from Redacted (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31)`

**Comment by Anon666333** [comment] 2023-11-27 03:26
Anyone else still getting this error...
I had two accounts and my main account stopped working in September, but my second account still worked. 
I continued to just use the secondary account without much issue, but am now getting this same error for _both_ accounts! 
Both accounts are in the same region.....I have no idea what's going on here.
Any assistance/advice would be greatly appreciated.
Same exact error as above.
