### ISSUE TITLE
Spotify card not showing playlists nor speakers after update to V4.0.0

### ISSUE THREAD

**Issue by XalaTheShepard** [fondberg/spotcast#473] opened 2024-11-07 14:54 UTC
Dear all, 

I have just updated to version 4.0.0 of Spotcast after updating yesterday to HA Core 2024.11.0 .
The Spotcast integration is able to start Spotify playlists, but the Spotify card is no longer showing the playlists nor the speakers. 
No issue could be found in the logs. 

Many thanks for all your support. 

Kind regards, 

Robin

**Comment by XalaTheShepard** [comment] 2024-11-07 15:33
Dear fcusson, many thanks for the information.
If I understand correctly the Spotify card, as we currently know, will disappear or be replaced?
Unless someone is able to repair the architecture of it.

**Comment by fcusson** [comment] 2024-11-07 15:56
Hi @XalaTheShepard,

For the current standpoint, I beleive @fondberg was the only maintainer with write access to the project. Because of that, the project is currently an abandonware since nobody has the ability to write to the source code. Someone would have to step in and fork the project to be able to revive it. This will become a necessity with the rewrite of spotcast I am doing, since I am updating the whole underlying architecture and that will very possibly break the way the way spotify-card work. If someone was actively developping the project, I could work with them to ensure we have a solution to make the 2 projects work together, but without that, I'm either stuck, only fixing bugs and mever improving spotcast or breaking spotify-card down the line.

The current situation looks like the changes in library for the main spotify integration broke spotify-card, since all th websocket endpoints and sensors (which are what spotify-card uses) are working as intended and provid the expected information

**Comment by XalaTheShepard** [comment] 2024-11-07 16:07
Dear fcusson, I wish I could help with that, but am afraid I have no Python skills.
If the change is only time consuming and I get the right directions, I am more than willing to help

**Comment by fcusson** [comment] 2024-11-07 16:09
We would need someone with experience in TypeScript for the spotify-card

**Comment by XalaTheShepard** [comment] 2024-11-07 16:17
This week will be impossible for me, but next week I will have a look to see if I can be of any help. Also no experience with TypeScript, but willing to learn and help 🙂

**Comment by mikevanes** [comment] 2024-11-07 21:14
I am looking into this, however I already have my own fork of the spotify-card, will post here to if I found the fix.

**Comment by mikevanes** [comment] 2024-11-07 21:29
Already found the fix, it is quite easily fixed. 

The ConnectDevice interface was defined wrong after the change it should look like this:

```TS
export interface ConnectDevice {
  device_id: string;
  is_active: boolean;
  is_private_session: boolean;
  is_restricted: boolean;
  name: string;
  device_type: string;
  volume_percent: number;
}
```

And than change the `fetchDevices` method to this:

```TS
private async fetchDevices(): Promise<void> {
  const message: Message = {
    type: 'spotcast/devices',
    account: this.parent.config.account,
  };
  try {
    const res: Array<ConnectDevice> = await this.parent.hass.callWS(message);
    this.parent.devices = res;
    
  } catch (e) {
    throw Error('Failed to fetch devices: ' + e);
  }
}
```

**Comment by mikevanes** [comment] 2024-11-07 21:31
I will fork the old codebase tomorrow and make the fix available if anyone is unsure how to do this.

**Comment by XalaTheShepard** [comment] 2024-11-07 22:00
Dear Mikevanes, 

Many thanks for already looking into the issue.

Kind regards,

Robin

**Comment by mikevanes** [comment] 2024-11-08 07:02
This fork contains a fix: https://github.com/mikevanes/spotify-card-v2 it also adds another playlist option: "recently-played", I prefer to use that playlist option. 

It is not available through HACS yet, so you have to install it manually which is easy enough.

**Comment by fcusson** [comment] 2024-11-08 10:44
Not at all thanks for taking the time on it glad to see the project getting revived.

**Comment by DiederichsAC** [comment] 2024-11-08 11:32
@mikevanes That's awesome. Many thanks for that. 

Not only fixing the bug, instead adding the **most useful** Playlist Option.

**Comment by fcusson** [comment] 2024-11-08 15:48
Since there is an open ticket on the Spotify Card repo, I'll close this one as resolve. 

@mikevanes, we'll need to have a chat soon-ish because of the refactor I'm working on for spotcast. You can track the changes [here](https://github.com/fcusson/spotcast/tree/feature/v4-rewrite). With the heavy change in Spotcast architecture and the move to a config entry base setup instead of yaml base, I fully expect spotify-card to break when I release the next major version. We can talk about the new architecture and how to proerly implement the spotify card for.

Currently, websocket API are not implemented in this build, I want to finalize the service calls first.

**Closed by fcusson** 2024-11-08 15:48 UTC
Labels: not a bug
