### ISSUE TITLE
Unmet dependencies (bs4 and lxml)

### ISSUE THREAD

**Issue by Blogem** [fondberg/spotcast#38] opened 2019-11-16 15:24 UTC
I installed spotcast trough hacs. After installing and configuring, I got the following error when calling spotcast.start: No module named 'bs4'

After installing BeautifulSoup4 in the virtualenv, I received the following error: bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

After installing this one in the virtualenv and restarting homeassistant, everything is working.

I kinda expected that these dependencies would be solved by hacs or otherwise get mentioned in the readme.

Everything is working now, so I'm happy :).

**Comment by fondberg** [comment] 2019-11-20 08:39
Weird that a non imported file should make this happen. I have now removed it and bs4 should no longer be necessary

**Comment by fondberg** [comment] 2019-11-20 08:44
Please try again with version v2.5

**Comment by soldag** [comment] 2019-12-10 21:36
I had the same issue. Seems to be caused by missing dependencies in https://github.com/soldag/spotify-webplayer-token/blob/master/setup.py.

I fixed this in https://github.com/enriquegh/spotify-webplayer-token/pull/3. After the PR has been merged and released, version of `spotify_token` dependency needs to be bumped here.

**Comment by fondberg** [comment] 2019-12-11 18:39
So the token library needed the dependency which it hadn't in the version spotcast listed?

**Comment by soldag** [comment] 2019-12-11 21:28
Yes, right. They are actually listed in [requirements.txt](https://github.com/enriquegh/spotify-webplayer-token/blob/master/requirements.txt), but not in [setup.py](https://github.com/enriquegh/spotify-webplayer-token/blob/master/setup.py), which is taken into account when installing it via pip.

**Comment by rhannink** [comment] 2019-12-16 11:19
Hallo,

I did:

```
source /srv/homeassistant/bin/activate
pip3 install lxml
pip3 install BeautifulSoup4
```

But Home Assistant is still complaining about the passer: `bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`

Any idea why it is still complaining? Python 3.7 on hassbian and HA 0.102 installeer.

**Comment by fondberg** [comment] 2019-12-17 13:12
@soldag until the PR is merged in spotify_token, do you have a suggestion on how to deal with this?

**Comment by soldag** [comment] 2019-12-17 13:25
You could add the missing requirements to the manifest of spotcast again as a workaround until the issue is fixed in `spotify_token`.

Don't know why installing them manually didn't fix the error for @rhannink, though :man_shrugging:

**Comment by enriquegh** [comment] 2020-01-02 18:33
@fondberg @soldag pinged you in the other thread but I've released 0.1.2 with soldag's fix.
Thanks again!

**Comment by fondberg** [comment] 2020-01-05 14:47
Thanks @enriquegh !

**Closed** 2020-01-05 14:47 UTC
