### ISSUE TITLE
Module 'pychromecast' has no attribute 'get_chromecast_from_cast_info'

### ISSUE THREAD

**Issue by MrRubberDucky99** [fondberg/spotcast#193] opened 2021-04-15 13:43 UTC
When I try to play a spotify playlist to my google home, I get this error 
```Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:526
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:19:28 (7 occurrences)
Last logged: 14:33:37

[34694755904] module 'pychromecast' has no attribute 'get_chromecast_from_cast_info'
[34686494416] module 'pychromecast' has no attribute 'get_chromecast_from_cast_info'
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/script/__init__.py", line 218, in service_handler
    await script_entity.async_turn_on(
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/script/__init__.py", line 323, in async_turn_on
    await coro
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 1041, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 254, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 262, in _async_step
    await getattr(
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 463, in _async_call_service_step
    await service_task
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1527, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/homeassistant/custom_components/spotcast/__init__.py", line 369, in start_casting
    spotify_cast_device = SpotifyCastDevice(
  File "/home/homeassistant/homeassistant/custom_components/spotcast/__init__.py", line 502, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/home/homeassistant/homeassistant/custom_components/spotcast/__init__.py", line 526, in getChromecastDevice
    return pychromecast.get_chromecast_from_cast_info(
AttributeError: module 'pychromecast' has no attribute 'get_chromecast_from_cast_info'
```

Is anyone able to help me fix this?
Thanks!

**Comment by hmmbob** [comment] 2021-04-15 13:47
Duplicate of #183

Update your HA and it should be solved 🤷🏻

**Comment by fondberg** [comment] 2021-04-17 12:45
Closing as this is documented in manifest.json as well as numerous closed other places

**Closed by fondberg** 2021-04-17 12:45 UTC
