### ISSUE TITLE
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player:  Device not found, reason: None

### ISSUE THREAD

**Issue by Mika255** [fondberg/spotcast#378] opened 2023-02-20 16:07 UTC
# Bug Ticket

## Describe the bug

I am using Spotify Premium and i am trying to switch playback from my Macbook desktop app and my Amazon Echo Show.
The switch works perfectly FROM my Amazon Echo Show (Mikaels Echo Küche) to my Macbook.
Unfortunately, the switch doesn't work the other way around and I'm getting the following message:

```
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player:
 Device not found, reason: None
```

I have regenerated the Client ID / Secret.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [x] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [Supervised]
 - HA version: [ Home Assistant 2023.2.5]
 - spotcast version: [3.7.0 ]

## Configuration

My device ID fetched via
https://developer.spotify.com/console/get-users-available-devices/
```` 
    {
      "id": "b694c2fe-b102-46f6-b4b1-903f7cbcff5c_amzn_1",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Mikaels Echo Küche",
      "type": "Speaker",
      "volume_percent": 45
    },
````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
service: spotcast.start
data:
  device_name: "Mikaels Echo Küche"
  spotify_device_id: b694c2fe-b102-46f6-b4b1-903f7cbcff5c_amzn_1
  entity_id: media_player.spotify_hell255
  force_playback: true
````

## Logs

* normal

````log
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:232
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 15:48:23 (9 occurrences)
Last logged: 17:02:32

    [140221505362992] Error handling message: Unknown error (unknown_error) from 192.168.1.77 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0)
    [140221498350688] Error handling message: Unknown error (unknown_error) from 192.168.1.77 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0)
    [140221916109728] Error handling message: Unknown error (unknown_error) from 192.168.1.77 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0)
    [140221497674144] Error handling message: Unknown error (unknown_error) from 192.168.1.77 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0)

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 269, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1830, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 232, in start_casting
    client.transfer_playback(
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 1778, in transfer_playback
    return self._put("me/player", payload=data)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 336, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 291, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player:
 Device not found, reason: None
````

## Additional context

<Add any other context about the problem here.>

**Comment by Mika255** [comment] 2023-02-20 16:13
I have also tried via

```
service: media_player.select_source
data:
  entity_id: media_player.spotify_hell255
  source: "Mikaels Echo Küche"
```

Gives me the following logs
`2023-02-20 17:12:02.458 ERROR (SyncWorker_3) [spotipy.client] HTTP Error for PUT to https://api.spotify.com/v1/me/player with Params: {} returned 404 due to Device not found`

**Comment by Mika255** [comment] 2023-02-20 16:37
Even the official spotify API isn't working...

https://developer.spotify.com/console/put-play/

`curl -X "PUT" "https://api.spotify.com/v1/me/player/pause?device_id=b694c2fe-b102-46f6-b4b1-903f7cbcff5c_amzn_1" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer XXXX"`

```
{
  "error": {
    "status": 404,
    "message": "Device not found"
  }
}
```

**Comment by fcusson** [comment] 2023-02-20 20:29
@Mika255 

> Even the official spotify API isn't working...

That api call will only work for devices already listed in `get-available-devices` call ([see here](https://developer.spotify.com/console/get-users-available-devices/)). If your device is not listed here, that will cause a problem. More over, Spotcast is ment to ensure the device is available in the list before trying the playback call.

This might not be extremely clear in the documentation, rewording it might be usefull, but the device name is for chromecast device only. We use it to find the device inside the list of devices provided by google through the googlecast integration. It does not work with other media speaker provided.

Normally the code should disregard the device name and go straight for the spotify_id, but could you still try to run with just the spotify_id, no device_name if the service call? I expect the same result, but I still prefer that we try.

**Comment by Mika255** [comment] 2023-02-20 21:24
I've removed my Amazon Spotify integration and reset it . 

Then I've removed the device_name from my service call, no luck either.
It's perfectly working when i between my Macbook, a web-player within my Macbook, my spotify app on my iphone.
Only switching to any Amazon (Show, Echo Dot, Fire TV) devices is not working....

```
service: spotcast.start
data:
  spotify_device_id: de2bd28a-5959-40ac-b03c-dc500d7368f8_amzn_1
  entity_id: media_player.spotify_hell255
  force_playback: true
```

```
2023-02-20 22:19:06.994 ERROR (SyncWorker_7) [spotipy.client] HTTP Error for PUT to https://api.spotify.com/v1/me/player with Params: {} returned 404 due to Device not found
2023-02-20 22:19:06.996 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: http status: 404, code:-1 - https://api.spotify.com/v1/me/player:
Device not found, reason: None
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 269, in _internal_call
response.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1830, in _execute_service
await self._hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/spotcast/__init__.py", line 232, in start_casting
client.transfer_playback(
File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 1778, in transfer_playback
return self._put("me/player", payload=data)
File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 336, in _put
return self._internal_call("PUT", url, payload, kwargs)
File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 291, in _internal_call
raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player:
Device not found, reason: None
2023-02-20 22:19:06.998 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140221387511728] Error handling message: Unknown error (unknown_error) from 192.168.1.77 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0)
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 269, in _internal_call
response.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1830, in _execute_service
await self._hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/spotcast/__init__.py", line 232, in start_casting
client.transfer_playback(
File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 1778, in transfer_playback
return self._put("me/player", payload=data)
File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 336, in _put
return self._internal_call("PUT", url, payload, kwargs)
File "/usr/local/lib/python3.10/site-packages/spotipy/client.py", line 291, in _internal_call
raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player:
Device not found, reason: None
```

Here my full list 
```
{
  "devices": [
    {
      "id": "a784317dc72596ab287b4c9c00711b4bffd4f663",
      "is_active": true,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Mikael's 2nd Fire TV",
      "type": "TV",
      "volume_percent": 0
    },
    {
      "id": "d236c501d79bc4c62901232a090c8b0f22389c74",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "MacBook Air (2)",
      "type": "Computer",
      "volume_percent": 63
    },
    {
      "id": "de2bd28a-5959-40ac-b03c-dc500d7368f8_amzn_2",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Überall",
      "type": "Speaker",
      "volume_percent": 49
    },
    {
      "id": "de2bd28a-5959-40ac-b03c-dc500d7368f8_amzn_1",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Mikaels Echo Küche",
      "type": "Speaker",
      "volume_percent": 49
    },
    {
      "id": "fcfa234a-959a-4f79-98a1-7c76d0ff3dcd_amzn_1",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Mikaels Echo Dot",
      "type": "Speaker",
      "volume_percent": 33
    },
    {
      "id": "7ef8768c-9bf7-4600-8f4f-89281ea0d2bf_amzn_1",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Mikaels Echo Klo",
      "type": "Speaker",
      "volume_percent": 32
    }
  ]
}
```

**Comment by berkansezer77** [comment] 2023-02-21 04:06
I am having the same issue. It started this morning. There is porbably a problem with spotify api.

**Comment by fcusson** [comment] 2023-02-21 11:10
@berkansezer77 

> I am having the same issue. It started this morning. There is probably a problem with spotify api. 

No there is no problem with the spotify api, working fine here. The 404 error is the most common one with Spotify integration, you could have a completely different reason for the failure.

Were you trying to transfer playback from a computer to an echo device?

**Comment by dazjones** [comment] 2023-02-21 11:24
I also have the same issue. I've managed to work around a bit as it works if you remove the `_amzn_X` part from the ID so `de2bd28a-5959-40ac-b03c-dc500d7368f8_amzn_2` becomes `de2bd28a-5959-40ac-b03c-dc500d7368f8`.

While this still won't fix anything for most folk, it at least points in the direction of the issue.

**Comment by Mika255** [comment] 2023-02-21 11:28
Amazing @dazjones , this worked for me too!

Changed from 
`e3938dc8-6c95-4c24-9e42-af984deb9494_amzn_1`

to 
```
service: spotcast.start
data:
  spotify_device_id: e3938dc8-6c95-4c24-9e42-af984deb9494
  entity_id: media_player.spotify_hell255
  force_playback: true
```

**Comment by Mika255** [comment] 2023-02-21 12:12
Ah, crap, my "Überall" (=plays music on all Amazon devices) and my "Echo Küche" device have the same ID if i'm removing the __amzn_ parts. Let's do a factory reset ;-)
```

    {
      "id": "e3938dc8-6c95-4c24-9e42-af984deb9494_amzn_2",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Überall",
      "type": "Speaker",
      "volume_percent": 41
    },
    {
      "id": "e3938dc8-6c95-4c24-9e42-af984deb9494_amzn_1",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Mikaels Echo Küche",
      "type": "Speaker",
      "volume_percent": 41
    },
```

**Comment by dazjones** [comment] 2023-02-21 12:41
Ah yes, I also have the same issue where a speaker and speaker group have the same ID without the `amzn` prefix. Unfortunately I don't see a workaround for that right now.

**Comment by liamkeefe9** [comment] 2023-02-21 16:23
Same issue here and the exact same results when troubleshooting all of what @Mika255 has done so far.

I also noticed that removing the "_amzn_X" part of the device ID works, so not sure if the Device ID's have changed recently -Can't say I've made a note of these before.

I was using this as intended as recently as 4PM GMT on 20/02 so something has changed in the last 24 hours. I tried using the card again this morning and I get the mentioned error.

When I try using the Device Name in the Spotcast call, I get "Error running action, Unknown error". If I purposely mistype the Device Name, it tells me: "Error running action, Could not find device with name XXXX". So it knows the device is there, just can't connect for some reason.

**Comment by fcusson** [comment] 2023-02-21 17:48
Ok seems the problem is with a change in amazon's implementation of spotify id.

Did a factory reset resolves the problem, that should normally provide a new id

**Comment by farridav** [comment] 2023-02-22 14:31
A factory reset of what exactly ?  I'm having the same issue with suffixes..

**Comment by fcusson** [comment] 2023-02-22 15:42
> A factory reset of what exactly ? I'm having the same issue with suffixes..

of an echo speaker. I want to see if the problem is that Amazon changed there way of managing spotify_ids. It might give a different spotify_id without the suffixes on new setup now. The change seems extremely recent.

**Comment by elkay98** [comment] 2023-02-22 16:51
> > A factory reset of what exactly ? I'm having the same issue with suffixes..
> 
> of an echo speaker. I want to see if the problem is that Amazon changed there way of managing spotify_ids. It might give a different spotify_id without the suffixes on new setup now. The change seems extremely recent.

Unfortunately not for me. I factory reset my Echo and set back up, but I still get the "_amzn_1" appended to the device ID. Spotcast is still in the same state as of right now.

If I trigger Spotify to play from my mobile device to the Kitchen Speaker, I see this on the card, so it is updating:

![image](https://user-images.githubusercontent.com/105752592/220697403-84af5ec3-bc8a-4e33-82f3-123695eb7c87.png)

The previous, pause and next buttons work as intended and change the tracks on the Kitchen Speaker (This device has "_amzn_1" appended to its Device ID and is an Echo 3rd Generation).

I can even switch between devices on the card, but only to devices that don't have the "_amzn_X" in their Device ID. Fire TV's seem unaffected and work fine, but my two Echo's have the "_amzn_X" and don't do anything when selected.

![image](https://user-images.githubusercontent.com/105752592/220698023-6f553b21-85e7-417c-8def-3fbda9eee3bf.png)

**Comment by sekonicpr** [comment] 2023-02-22 16:53
I have the same problem using the scripts with the device_name.  I deregistered one of my Echos but the problem continues.  Where do I have to go to reset to default?

**Comment by woempiej** [comment] 2023-02-22 17:00
Same here with 6 freaking Echo's.
It works with an automation to start a playback as show below (via the info here I deleted the _amzn_X behind the DeviceID). Before I used only the Device name and that worked great for about 2 years.

![afbeelding](https://user-images.githubusercontent.com/62903344/220700399-3ec33243-4449-49a7-a9e9-283e554274b1.png)


This spotify dashboard card on the other hand is completly useless right now because I doens't start a playback

![afbeelding](https://user-images.githubusercontent.com/62903344/220701287-e61d5f7c-61d4-431c-a0d8-66ca84d731ee.png)

I get the below error when tapping a playlist

![afbeelding](https://user-images.githubusercontent.com/62903344/220701458-bd67aa4c-9bd0-4d46-9313-9ba86f9db017.png)

**Comment by elkay98** [comment] 2023-02-22 17:01
> I have the same problem using the scripts with the device_name.  I deregistered one of my Echos but the problem continues.  Where do I have to go to reset to default?
> 
> 

I went to the Amazon Alexa app, found the device, clicked the settings cog, scrolled down to the "Registered To" section and De-registered the device from my account. 

Alexa then told me she was going through a factory reset process and it may take a few minutes to complete.

Once complete, just set back up via the Amazon Alexa app.

**Comment by sekonicpr** [comment] 2023-02-22 17:24
> > I have the same problem using the scripts with the device_name.  I deregistered one of my Echos but the problem continues.  Where do I have to go to reset to default?
> > 
> > 
> 
> I went to the Amazon Alexa app, found the device, clicked the settings cog, scrolled down to the "Registered To" section and De-registered the device from my account. 
> 
> Alexa then told me she was going through a factory reset process and it may take a few minutes to complete.
> 
> Once complete, just set back up via the Amazon Alexa app.

Yep that were the steps I took but it continues with the same error.  I also deregister the spotify skill in the alexa app but no luck.

**Comment by fcusson** [comment] 2023-02-22 17:45
ok at that point, we should make sure of what spotify_id is reported in the `get-available-devices` api call. Can you make sure that spotify is playing something over the speaker and then make a get request to the get-available-devices endpoint? I want to check what device id is being reported.

**Comment by AeroV95** [comment] 2023-02-22 17:48
I have the exact issue. I have tried to reset one of the devices, but it added amz_1 at the end. Then I noticed that the issue shifted to the next speaker in the group. This seems to be affecting only speaker groups.

**Comment by elkay98** [comment] 2023-02-22 17:53
> ok at that point, we should make sure of what spotify_id is reported in the `get-available-devices` api call. Can you make sure that spotify is playing something over the speaker and then make a get request to the get-available-devices endpoint? I want to check what device id is being reported.

Here is the result for me when something is playing:

![image](https://user-images.githubusercontent.com/105752592/220713715-dcc81e8f-9e70-4ca0-af9e-ddba09e3c0fa.png)

**Comment by woempiej** [comment] 2023-02-22 17:54
@elkay98 

Very loud ;)

**Comment by fcusson** [comment] 2023-02-22 18:26
so.... the suffix is retain... I'll have to dig deeper, but the behavior is very strange

**Comment by Mika255** [comment] 2023-02-22 20:00
I have factory reset both my Echo Show 8's, and both now have no _amzn_X suffix. 
However, my Echo Dot gen4 is still (even after 2 factory resets) keeping this _amazn_X suffix.

**Comment by Mika255** [comment] 2023-02-22 20:01
> I have the exact issue. I have tried to reset one of the devices, but it added amz_1 at the end. Then I noticed that the issue shifted to the next speaker in the group. This seems to be affecting only speaker groups.
> 
> EDIT: Affects all of the Echos'. I have 8.

Do you have Echo Dot's? What generation? What model?

**Comment by thePsychotrop** [comment] 2023-02-24 08:45
Same here. The "überall" group had the same ID as the echo dot (5th) and removing the _amzn_x worked. I killed the group since i don´t use it at the moment and now i can use spotcast again. But i used device names before and now ids.
The issue started the same day this threat was posted.

**Comment by galaxyrun** [comment] 2023-02-24 12:13
i have the same problem with my echo dot 3. gen

**Comment by AeroV95** [comment] 2023-02-25 06:49
> > I have the exact issue. I have tried to reset one of the devices, but it added amz_1 at the end. Then I noticed that the issue shifted to the next speaker in the group. This seems to be affecting only speaker groups.
> > EDIT: Affects all of the Echos'. I have 8.
> 
> Do you have Echo Dot's? What generation? What model?

From the 3rd to the 5th generation, all have this issue.

**Comment by lollozzo** [comment] 2023-02-25 15:51
Fixed this way using device id without suffix "_amzn_1":
- 2 tasks automation:
First: set playlist on spotify
Then: spotcast play without content, just force play last content

This is the only way to workaround unavailable problems, switching echo errors, device not found etc.

Hope you find this helpful!
Greetings

alias: Music Test
sequence:
  - service: media_player.play_media
    data:
      media_content_type: playlist
      enqueue: play
      media_content_id: >-
        https://open.spotify.com/playlist/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
    target:
      entity_id: media_player.spotify_andrea
  - service: spotcast.start
    data:
      start_volume: 30
      force_playback: true
      spotify_device_id: "DEVICE_ID_WITHOUT_amzn_1"
      limit: 20
      random_song: false
      repeat: "off"
      shuffle: false
      offset: 0
      ignore_fully_played: false
    enabled: true
mode: single

**Comment by fcusson** [comment] 2023-02-25 18:18
> Fixed this way using device id without suffix "_amzn_1

Yes somebody else in the thread did found that also, the only problem is that in turns out that multiple device can have the same device I'd when removing the suffix. At this point there isn't much that can be done from this project's side since we are reliant on Spotify API. We have no idea if Amazon does something specific to make the devices correctly available to them.

**Comment by AeroV95** [comment] 2023-02-26 06:38
> > Fixed this way using device id without suffix "_amzn_1
> 
> Yes somebody else in the thread did found that also, the only problem is that in turns out that multiple device can have the same device I'd when removing the suffix. At this point there isn't much that can be done from this project's side since we are reliant on Spotify API. We have no idea if Amazon does something specific to make the devices correctly available to them.

Do you think if there a chance of this getting fixed or are we dependent on Spotify?

**Comment by bremor** [comment] 2023-02-28 01:01
I was experiencing this issue, but it has now resolved itself without any changes on my end.

**Comment by elkay98** [comment] 2023-03-01 16:00
Same here.

I tested again after I'd seen @bremor's reply and this now works for me again. With this working, I run another check on the 'Get Available Devices' Spotify API and my speakers still have the "_amzn_1" in the device ID.

Not sure what has changed or who has changed something, but it's working again!

**Comment by fcusson** [comment] 2023-03-02 22:28
> Not sure what has changed or who has changed something, but it's working again!

Seems to be a bug on Amazon's end. Glad they resolved semi-quickly.

**Closed by fcusson** 2023-03-02 22:28 UTC
Labels: bug

**Comment by Mika255** [comment] 2023-03-04 11:39
Yes, works for me too now! Awesome. Thanks @bremor
