### ISSUE TITLE
When switching Cast Device - Music was stopped because spotify was used at a different device

### ISSUE THREAD

**Issue by VaillantHassIo** [fondberg/spotcast#323] opened 2022-04-25 05:47 UTC
# Bug Ticket

## Describe the bug

* [x ] Using latest version of spotcast
* [x ] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x ] Using latest stable version of Home Assistant
* [ ] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: HA_OS
 - HA version: 2022.4.6
 - spotcast version: 3.6.29

## Configuration

- out of the box spotify + spotcast

## Service Call

- not required as issue is replicable with integrated Media Player Selection

## Additional context

- my environment is mostly Google Nest Audio + Mini + Google Home Speaker Groups
- when switching Devices via Media Player Selection
--> the playback continues on new Device/Player
--> playback on former Device stops but brings message Music was stopped because spotify was used at a different device

- While this might be technically correct (works as designed), i wonder if a Stop can be initiated before player/device transition

- Any other workaround available eg. lower Volume of the Cast Device to 0 before transitioning?

I belive this is not(?) related to https://github.com/fondberg/spotcast/issues/13

**Comment by fcusson** [comment] 2022-04-25 13:02
Hi @VaillantHassIo, I would consider this more of an improvement option than a bug. The following is primarily to document so people can pitch in on their idea for improvement

I can confirm yes this would be the appropriate behavior, but that's because we don't have control over the way the media_selector makes the transfer.

Basically, Spotcast already has a way to transfer playback, you simply call the `spotcast.start` without any media data (no URI, search query or category) and it will do just that transfer the playback, but if you transfer the playback and change media at the same time, the API sees that as the account being overtaken by the new media source and sends that message.

I could try and simply add a stop media before the rest of the start method, but we will have to test if this creates problem in seamlessness in general for the integration.

**Comment by VaillantHassIo** [comment] 2022-04-25 15:15
thx for reply. 

- i was not changing the media data, are you saying the spotcast media selector is different from spotcast.start?
- i also tried spotcast.start causing the same behavior, no change in media but the message is being broadcasted
--> the actual behavior is more likely compared to google home when i go to a differnt Nest Device and want it to play something using voice commands
--> however using Google Home, i can also just select a different cast device playing the same media and it works

So transition to a different device should work flawlessly, thats what you are saying? as long as no new media is being started. ( which is not the case unfortunately )

**Comment by fcusson** [comment] 2022-04-25 19:42
> i was not changing the media data, are you saying the spotcast media selector is different from spotcast.start?

I'm not sure I'm following you, because I'm unaware of a way to change the media source without selecting a media in the media selector. Just to make sure we are talking about the same thing: Are you talking about the media tab in the left menu of your dashboard when you refer to the media player selector (or the pop-up menu on the `media_player` itself)? Or something else?

Also, how do you go about changing the source?

After testing, it seems the transfer playback solution we have (`spotcast.start` without media data) sends the "used on another device" message also, which is a regression because it wasn't supposed to do it anymore. A change in the API might be causing that. We would have to check if it's possible to circumvent that. It could be possible that we are stuck with the message if we don't want to sacrifice usability.

**Comment by VaillantHassIo** [comment] 2022-04-26 04:27
> change in the API might be causing that. We would have to check if it's possible to circumvent that. It could be possible that we are stuck with the message if we don't want to sacrifice usability.

I had a typo. Its the CastDevice Selector not Media Selector. But your statement above basically narrow it down, this being a regression. Do you have a Reference Issue for that? 

I am gonna try to see if the automation (script) in HA can send a stop before start playback on another device.

Feel free to close this issue. Many thx again

**Comment by fcusson** [comment] 2022-04-26 11:57
That is something we could look into in the process flow of Spotcast, I won't close the issue to keep documentation on a potential improvement.

**Comment by fcusson** [comment] 2024-12-05 13:52
@VaillantHassIo no longer seems to be a problem lately with the different improvements. Can you confirm if you still have the issue?

**Closed** 2024-12-10 13:55 UTC
Labels: enhancement
