### ISSUE TITLE
The list of albums does not appear and every time I restart the sp_key and sp_cd it is different and I have to change it

### ISSUE THREAD

**Issue by javiges** [fondberg/spotcast#442] opened 2024-05-06 13:03 UTC
# Bug Ticket

## Describe the bug
I don't get the list of albums listened to and every time I restart the sp_dc and the sp_key changes, it's different and I change it to the new codes and they don't work, and I restart and new ones appear, I don't know what to do anymore

I don't know why every time I restart the sp_dc and sp_key the changes are different and the problem continues, the list of albums does not appear on the card.

I have deleted the cookies and nothing still fails

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [* ] Using latest version of spotcast
* [* ] Using latest stable version of Home Assistant
* [* ] I have setup the Spotify integration in Home Assistant
* [ *] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [* ] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: HA_Container
 - HA version: [2024.5.1 ]
 - spotcast version: [3.7.3 ]

````

## Logs

2024-05-06 12:49:23.493 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'spotcast' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/spotcast/__init__.py, line 163: hass.async_add_job(get_player()), please create a bug report at https://github.com/fondberg/spotcast/issues

**Comment by fcusson** [comment] 2024-05-06 16:55
@javiges the spotify token information will always change after a new login that's by design, otherwise someone would be able to take your old cookie and impersonate you.

What card are you talking about, this project does not maintain any front-end elements, if you are talking about the spotify Lovelace card, this is a separate project and would require you to open a ticket with them. We are only a dépendance of the project.

Without much detail given, I would first check if you have the sensor active, this is a requirement for the spotify Lovelace card.

Also you can disregard the log item you have this is mentioning a deprecation coming in April 2025 we are already working on moving to the new methods.

**Comment by javiges** [comment] 2024-05-07 06:31
Thank you very much for all the information

**Comment by javiges** [comment] 2024-05-07 06:37
> @javiges the spotify token information will always change after a new login that's by design, otherwise someone would be able to take your old cookie and impersonate you.
> 
> What card are you talking about, this project does not maintain any front-end elements, if you are talking about the spotify Lovelace card, this is a separate project and would require you to open a ticket with them. We are only a dépendance of the project.
> 
> Without much detail given, I would first check if you have the sensor active, this is a requirement for the spotify Lovelace card.
> 
> Also you can disregard the log item you have this is mentioning a deprecation coming in April 2025 we are already working on moving to the new methods.

What do you mean by active sensor?

**Comment by fcusson** [comment] 2024-05-07 20:03
the [sensor](https://github.com/fondberg/spotcast#use-the-sensor) documented in the readme that is a requirements for spotify-card.

Just for clarification, I don't mean the active sensor, but to make sure the sensor **is** active.

**Comment by fcusson** [comment] 2024-07-01 23:37
No reply in almost two months. @javiges can we close your issue?

**Comment by fcusson** [comment] 2024-07-22 11:52
Closing for inactivity

**Closed** 2024-07-22 11:52 UTC
Labels: bug
