### ISSUE TITLE
Device not found for Google devices.

### ISSUE THREAD

**Issue by ajkelsey** [fondberg/spotcast#337] opened 2022-07-26 14:15 UTC
# Bug Ticket

## Describe the bug

* [X ] Using latest version of spotcast
* [ X] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ ] Using latest stable version of Home Assistant
* [ X] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ X] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [Core]
 - HA version: [ core-2022.7.6]
 - spotcast version: [ 3.6.29]

## Configuration

Add your configuration

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

## Additional context

If the Google device has been given a custom name, spotcast will not be able to locate the device. This is true when using device name or entity_id. When I removed the custom name, it would function properly. This may be an issue with HA, but adding this information to the documentation would be very helpful.

**Comment by Maaxion** [comment] 2022-07-26 20:52
Please also include the logs of the error you received, and preferrably debug logs, too. 

This sounds like it could be a duplicate of https://github.com/fondberg/spotcast/issues/334

**Comment by ajkelsey** [comment] 2022-07-27 17:21
I went and configured a custom name for my Google Home then attempted to play a spotify playlist. For debug, I configured homeassistant.spotcast.



Log:
> 2022-07-27 13:16:55 ERROR (SyncWorker_6) [custom_components.spotcast.spotcast_controller] Could not find device Kitchen Speaker from hass.data
2022-07-27 13:16:55 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall spotcast.start (c:01G90AJN39FYMHMF7E45C4CNEW): entity_id=media_player.kitchen_speaker, uri=spotify:playlist:0X5Rx2f0PXjkvDCuxgnRrY, repeat=off, offset=0, start_volume=101, shuffle=False, random_song=False, limit=20, ignore_fully_played=False, force_playback=False>
Traceback (most recent call last):
File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1731, in catch_exceptions
await coro_or_task
File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1756, in _execute_service
await self._hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/homeassistant/homeassistant/custom_components/spotcast/__init__.py", line 190, in start_casting
spotify_device_id = spotcast_controller.get_spotify_device_id(
File "/home/homeassistant/homeassistant/custom_components/spotcast/spotcast_controller.py", line 203, in get_spotify_device_id
spotify_cast_device = SpotifyCastDevice(
File "/home/homeassistant/homeassistant/custom_components/spotcast/spotcast_controller.py", line 55, in __init__
self.castDevice = self.getChromecastDevice(device_name)
File "/home/homeassistant/homeassistant/custom_components/spotcast/spotcast_controller.py", line 81, in getChromecastDevice
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Could not find device with name Kitchen Speaker

**Comment by fcusson** [comment] 2022-08-06 11:53
is duplicate see #334

**Closed by fcusson** 2022-08-06 11:53 UTC
Labels: bug
