### ISSUE TITLE
Cast device not launching properly, but works if timeout is ignored

### ISSUE THREAD

**Issue by Gramatus** [fondberg/spotcast#365] opened 2022-11-27 18:04 UTC
# Bug Ticket

## Describe the bug

I am not sure if this is relevant for anyone else, but in case it creeps up other places I decided to create a report as I have a solution _if_ anyone else experiences the same problem.
Basically it seems my cast devices has some sort of issue with starting properly. This does not only include spotcast, but also when trying to cast Spotify from the web player. Most of my devices are Chromecast audio, but I also have a few normal Chromecasts.
What happens is the app is started (I hear the "startup sound"), but not totally started (on the normal chromecasts, the screen goes black).

Now, what I discovered is that this causes Spotcast to fail because the `is_launched` property of the `SpotifyController` class stays false. However, if I ignore that and simply try to start playing anyways everything works fine.

If this becomes a problem, and not just something happening on my setup, it seems it can be fixed by ignoring that `is_launched` is False.
If no one else experiences the same, feel free to ignore this as I have fixed the issue for myself.

I made these changes to Spotcast, and now everything seems to work for me:

1. Spotify_controller.py, line 104 to 106 changed to:
```
            # raise LaunchError(
            #     "Timeout when waiting for status response from Spotify app"
            # )
            self.logger.warning("Timeout when waiting for status response from Spotify app")
```
2. Spotcast_controller.py, linje 94-96 changed to:
```
            # raise HomeAssistantError(
            #     "Failed to launch spotify controller due to timeout"
            # )
            _LOGGER.warning("Spotify controller did not launch properly before timeout, this might not be a problem")
```

* [x] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have Spotify Premium
* [ ] I am using multiple accounts
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: HA_OS
 - HA version: 2022.11.4
 - spotcast version: 3.6.29 (but I have manually included the fix from 3.6.30)

## Configuration

Add your configuration

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

**Comment by DanDixon** [comment] 2022-11-27 19:52
This fixed the problem for me that I reported:
https://community.home-assistant.io/t/spotcast-custom-component-to-start-playback-on-an-idle-chromecast-device/114232/911?u=ozstone

Thank you so much, @Gramatus 

And a massive thanks to @fondberg for making this in the first place. Doing away with trying to start music on speaker groups using Google Assistant was an awful experience that worked maybe half? the time. Thank you again!

Cheers to @fcusson for helping too!

**Comment by Johnito** [comment] 2022-11-27 22:38
@Gramatus thank you. Before your fix, I also had this issue and had to send the command to play something 2x to get it to past the startut sound

**Comment by jsv93** [comment] 2022-11-28 00:04
Thank you for posting this fix! Ive been chasing it for a number of hours now. I have tried implementing your fix however as soon as I modify spotcast_controller.py or spotify_controller.py and restart i get the following error:

`Component error: spotcast - Exception importing custom_components.spotcast`

Any ideas as to what im doing wrong?
In order to restart I have to re-download spotcast.

Cheers!

**Comment by jsv93** [comment] 2022-11-28 00:22
@Gramatus Thank you so much for posting this fix! I had been chasing this for hours on end. After adjusting as per your recomendation it is working again. Any idea what has caused this to happen?

**Comment by tasteebeverage** [comment] 2022-11-28 04:56
@Gramatus , thank you for this! I was banging my head against the wall trying to figure out what went wrong and the fix you described worked for me.

**Comment by Gramatus** [comment] 2022-11-28 06:30
> Any idea what has caused this to happen?

As far as I understand it, there seems to be an error in the Spotify Chromecast "app" (the thing running on the Chromecast). I base that on the fact that the same behaviour happens if I try to cast using Chrome.

As such this is a rather bad workaround and probably needs some smarter code if it is to be included in Spotcast, but as the other commenters have confirmed it seems to work for now.

**Comment by antonio1475** [comment] 2022-11-28 11:10
Thank you @Gramatus. Your changes work for me too.

The experience is not the original from months ago (Spotify logo > **10 seconds black screen** > starts playing) but it works at least! 😄 

Although I also see, as you mentioned, that casting from Spotify Chrome does the same (or even worse, it doesn't get to play for me! I'd be pissed if I was a normal user using Spotify web to cast, and not HA & Spotcast 😅 )

It also solves (directly or indirectly?) https://github.com/fondberg/spotcast/issues/334 , which I was working around it by repeating the Spotcast service twice.

**Comment by TheFes** [comment] 2022-11-28 12:06
There seem to me more issues regarding Spotify on Google Cast devices. I've noticed several times that the device reports as `idle` in Home Assistant while it is actively playing on Spotify

**Comment by robkjr** [comment] 2022-11-29 17:04
So I'm finding that this fix works but not for the first time initiated.  Example.  I have a mini media card setup with 4 Spotify station buttons.  The first time I click on a button, it initiates the speakers but fails to play the playlist.  Click the button again, and the playlist works fine.  From that point, any button/playlist works until the playlist is stopped and the speakers go back to idle/off.

**Comment by Johnito** [comment] 2022-11-30 22:51
@antonio1475 @robkjr yes, i do observe the very same things on my setup so this general. You can provoke this behaviour easily to test just by stopping the Google Nest entities (for exemple) and trying to launch the spotcast service again.

**Comment by robkjr** [comment] 2022-11-30 23:37
> 

Exactly.  The Google Nest/Cast items must be in the off state to see the behavior.

**Comment by Johnito** [comment] 2022-12-11 23:51
@robkjr i manually coopied [the changes implemented from this pull request](https://github.com/fondberg/spotcast/pull/366), and it works just fine now. 100% success whatever may be the initial cast devince state.

**Comment by Jaykurb** [comment] 2022-12-18 13:20
I'm trying to make the changes to the Spotify_controller.py & Spotcast_controller.py files but I must be doing something wrong. After I make the changes I check the configuration and it doesn't address any issues. However, after I restart HA Spotify breaks and I get the error:

`Setup failed for custom integration spotcast: Unable to import component: Exception importing custom_components.spotcast`

When I check the configuration after the reset it says the configuration is invalid with the error: 

`Component error: spotcast - Exception importing custom_components.spotcast`

Is anyone able to show how their files look after the changes, please?

**Comment by max246** [comment] 2023-01-05 14:43
Looks like the issue is back
https://community.home-assistant.io/t/spotcast-custom-component-to-start-playback-on-an-idle-chromecast-device/114232/918

but also for me:
2023-01-05 14:38:44.547 ERROR (MainThread) [homeassistant.components.automation.new_automation2] [Alarm] Bedroom alarm: Error executing script. Error for call_service at pos 2: Failed to get device id from Spotify

**Comment by antonio1475** [comment] 2023-01-06 22:44
> @robkjr i manually copied [the changes implemented from this pull request](https://github.com/fondberg/spotcast/pull/366), and it works just fine now. 100% success whatever may be the initial cast device state.

Yup, this seems to be working for me! Although it does generate errors

**Comment by fcusson** [comment] 2023-03-07 01:38
closing due to new release and no further report

**Closed by fcusson** 2023-03-07 01:38 UTC
Labels: bug

**Comment by wautersj** [comment] 2023-08-28 19:43
I'm experiencing this behaviour again. A lot like the comments above. 

It might have to do with Spotify changing their auth/handshake flow?

**Comment by cjborchert** [comment] 2023-08-28 20:20
@wautersj same thing here, although looks like there's a new ticket: #398

**Comment by wautersj** [comment] 2023-08-29 09:02
@cjborchert Thanks! Looks like the right thing!
