### ISSUE TITLE
crunching sound

### ISSUE THREAD

**Issue by tcarlsen** [fondberg/spotcast#194] opened 2021-04-16 08:21 UTC
since the new update with default Spotify integration, every time I use spotcast to start a playlist its making a crunching/crackling sound in the speaker with a 15-30 second interval.

No problem then starting Spotify via iOS

**Comment by fondberg** [comment] 2021-04-17 12:45
I can't reproduce. Can you create new sp_dc and sp_key and try again?

**Comment by peterjuras** [comment] 2021-04-18 06:07
I have a similar issue, but I'm not sure that it is due to spotcast. Even if I start spotify via a normal Google Assistant command the sound is crunchy for me.

**Comment by tcarlsen** [comment] 2021-04-18 07:32
Mine actually started doing the cracking sound after a google command as well. But nit as often as it does with spotcast. 
It started after the lastes update if spotcast snd of course the addition of the official spotify integration. 

I will try uninstalling spotcast only and see if it's stops. And then the official integration.

**Comment by gambith** [comment] 2021-04-18 09:46
Turn off the ultrasound sensing on your Google device, that fixed it for me

https://support.google.com/googlenest/answer/9509981?hl=en

**Comment by tcarlsen** [comment] 2021-04-19 07:22
@gambith turning og ultrasound does seem to stop the cracking. but having it on didnt make a cracking sound before the latest spotcast update. so some how these to are connected

**Comment by MrSuttonmann** [comment] 2021-04-22 09:39
@tcarlsen I've been having the crackling sound too, but I noticed it on Tuesday. I didn't have spotcast installed on HASS until this morning. I don't think the issue is related.

**Comment by tcarlsen** [comment] 2021-04-22 10:02
@MrSuttonmann odd. I only have it then its SpotCast thats starts the music 😕

**Comment by fondberg** [comment] 2021-04-26 10:42
I will close this as I can't imagine that spotcast is involved

**Closed by fondberg** 2021-04-26 10:42 UTC
