### ISSUE TITLE
HA 2021.4.0 - spotcast failed

### ISSUE THREAD

**Issue by rotrials** [fondberg/spotcast#174] opened 2021-04-07 20:33 UTC
Hello,

After updating to Home Assistant 2021.4.0

I got the following error for spotcast
Setup failed for spotcast: Unable to import component: cannot import name 'KNOWN_CHROMECAST_INFO_KEY' from 'homeassistant.components.cast.media_player' (/usr/src/homeassistant/homeassistant/components/cast/media_player.py)

Let me know if you need further details? 
Thanks for the project!

**Comment by Chimete** [comment] 2021-04-07 22:04
Hello, same error here

Thanks for the project!

**Comment by onkytonk** [comment] 2021-04-07 22:49
I've just encountered the same error myself.

**Comment by hbaez81** [comment] 2021-04-07 22:57
Same issue in 2021.4.0

**Comment by StreetGuru** [comment] 2021-04-07 23:13
Same issue after 2021.4 upgrade

**Comment by KaylaSiemon** [comment] 2021-04-08 00:23
Sam issue here

**Comment by justincrosby** [comment] 2021-04-08 06:04
Quick look through the new code and it looks like they've removed the KNOWN_CHROMECAST_INFO_KEY. The data is no longer stored in an easily accessible way. I don't see an obvious way to obtain this info now, but someone with more experience might be able to figure out a way.

**Comment by strandaster** [comment] 2021-04-08 06:43
This issue is a duplicate of #172. There is already a potential patch available.

**Comment by rotrials** [comment] 2021-04-08 06:47
Still, it should update automatically if it's fixed.

**Comment by michaeltryl** [comment] 2021-04-08 07:22
i can figuere out what the fix in #172 is. can someone tell me

**Comment by strandaster** [comment] 2021-04-08 08:18
> i can figuere out what the fix in #172 is. can someone tell me

@icarome created a pull request #173 with the needed code change to get it working in the new version of Home Assistant.

**Comment by ranrinc** [comment] 2021-04-08 08:30
Following the issues so I will get update when its fixed

**Comment by michaeltryl** [comment] 2021-04-08 08:35
> > i can figuere out what the fix in #172 is. can someone tell me
> 
> @icarome created a pull request #173 with the needed code change to get it working in the new version of Home Assistant.

Thanks i copy All the files to my install.
Then update home Assistant.
There came No notifikation with fail, but i could not start my playlist

**Comment by beasthouse-au** [comment] 2021-04-08 12:28
Also having this issue, following for a fix

**Comment by kireque** [comment] 2021-04-08 12:30
Following the issues so I will get update when its fixed

**Comment by Maaxion** [comment] 2021-04-08 13:01
Please do not comment unless you have relevant information regarding the issue at hand. Every time you comment everyone gets notified. If you wish to follow the issue click the thumbs up button on the first post. Posting non-informative comments is very disruptive.

**Comment by connor-dobbins** [comment] 2021-04-08 20:06
I am not sure if this is part of this issue or a different issue. I updated to 2021.4.0 and got the same error about 'KNOWN_CHROMECAST_INFO_KEY'. I then commented out the spotcast lines from the configuration.yml file and now Spotcast doesn't even showup in HACS

**Comment by TheBisk** [comment] 2021-04-09 10:23
Same issue in 2021.4.1

**Comment by michaeltryl** [comment] 2021-04-09 12:09
This worked for me. copy all these files over to your spotcast folder
https://github.com/raman325/spotcast/tree/fix_2021_4/custom_components/spotcast
then put this fix into the __init__.py file
https://github.com/fondberg/spotcast/commit/c6b29531fb0836c7665a020c18fc33a99fba9dc3

reboot your system and it should work again

**Comment by pergolafabio** [comment] 2021-04-09 12:39
i tried it, download complete folder , replaced, all files, then edited the init file, but after a restart , i got the issue thay spotcas integration could not be setup

**Comment by pergolafabio** [comment] 2021-04-09 12:47
if i do replace the complte folder, without this : https://github.com/fondberg/spotcast/commit/c6b29531fb0836c7665a020c18fc33a99fba9dc3

then  seems HA  to hangup on restart on a second time

**Comment by Electronlibre2012** [comment] 2021-04-09 12:53
Hello,

like @pergolafabio  doesnt work for me...

Home Assistant OS 5.13
supervisor-2021.03.9
core-2021.4.1

i tried the spotcast-fix_2021_4, doesnt work.

**Comment by pergolafabio** [comment] 2021-04-09 12:54
nah, it made it verry worse, had extreme issues starting HA, rolled back and now disabled that one

**Comment by WirelessMind** [comment] 2021-04-09 14:48
Integration disabled

**Comment by derandiunddasbo** [comment] 2021-04-09 18:14
A bit off topic, but the 'Check Home Assistant configuration' addon is really handy for spotting these kind of issues, before updating to a new HA version. I'm always running it before actually updating and for the current update it threw this error right away, keeping me from getting into trouble in the first place.

**Comment by alexwohlbruck** [comment] 2021-04-10 23:37
I tried removing the addon, but now when I check config I get:
```Component error: spotcast - No module named 'custom_components.spotcast'```
Is HA still referencing the module somewhere? How could I fix?

**Comment by kongo09** [comment] 2021-04-10 23:46
Are you sure you really removed it from your configuration? I had that as well until I discovered a sensor somewhere using spotcast.

**Comment by beasthouse-au** [comment] 2021-04-11 04:24
> Are you sure you really removed it from your configuration? I had that as well until I discovered a sensor somewhere using spotcast.

Do you remember which sensor? I’ve had a similar Invalid Config notification ever since the big update. Had removed spotcast but still have the error.

**Comment by alexwohlbruck** [comment] 2021-04-11 05:52
You're right, i forgot to remove the config in my yaml file. All gone!

**Comment by fondberg** [comment] 2021-04-11 11:51
I'm going to release a new version when https://github.com/home-assistant/core/pull/49045 is merged (should be today or tomorrow)

**Comment by johnjoemorgan** [comment] 2021-04-11 12:17
> 
> 
> I'm going to release a new version when [home-assistant/core#49045](https://github.com/home-assistant/core/pull/49045) is merged (should be today or tomorrow)

Very much appreciated

**Comment by fondberg** [comment] 2021-04-11 13:03
Fixed together with core PRs. Help me upvote them (links in this PR) https://github.com/fondberg/spotcast/pull/176

**Comment by hmmbob** [comment] 2021-04-11 13:11
To all users: saying thanks is nice, buying Niklas a coffee is even better. See https://github.com/fondberg/spotcast#donate

**Comment by frenck** [comment] 2021-04-11 14:04
> Fixed together with core PRs. Help me upvote them

That won't make a difference. At this point, the upstream PR is unneeded IMHO. Just dive into the entity/device registry of Home Assistant, get the instance of the entity and access the property directly.

That way:

- Home Assistant Core won't have custom code (which is not accepted in general)
- You can fix and distribute the issue faster and don't have to depend on the Home Assistant to release a patch.

**Comment by fondberg** [comment] 2021-04-11 14:31
@french i am sorry. I this is generally the way in other open source projects but i hear you in HA. 
Again sorry and people stop upvote!

**Comment by zhdenny** [comment] 2021-04-11 14:46
Sooooo....."Just dive into the entity/device registry of Home Assistant, get the instance of the entity and access the property directly."

That isn't really useful for someone who uses this simple integration. Can you explain to a simpleton like me....a lot of people use this integration and would love for it to work. I tried to read your [comment](https://github.com/home-assistant/core/pull/49045#issuecomment-817318061) but that doesn't really help me

**Comment by frenck** [comment] 2021-04-11 15:06
> That isn't really useful for someone who uses this simple integration. 

It wasn't directed at the "user", it was directed at developers working on the issue.

**Comment by kongo09** [comment] 2021-04-11 15:30
> That won't make a difference (the upvoting that is).

What should make a difference are the new analytics. To quote the release notes:

> So why do we do this? Well, it helps the project and all contributors to see things like: Most used integrations. This can significantly help with improving project priorities.

Right now, spotcast seems to have dropped from the list, as everyone has disabled it. I don't know, where it was before, but maybe the internal data of the project team can show this?

@frenck The release notes don't even mention that 2021.4.0 is breaking spotcast. So how exactly do the improved project priorities help now?

@fondberg Unfortunately, I'm not a developer and cannot help. Are you seriously intending to drop development of spotcast if you don't get your fixes approved? What kind of help and priorities from the project would you need to get this back working?

**Comment by frenck** [comment] 2021-04-11 15:31
> What should make a difference are the new analytics.

Those measure core integration, not custom ones.

**Comment by kongo09** [comment] 2021-04-11 15:39
@frenck apologies, I wasn't aware of that distinction. But then, I'm just a user and shouldn't have to.

**Comment by Electronlibre2012** [comment] 2021-04-11 15:39
If Spotcast still custom, is that just mean the HA Team doesnt find interesting to include it as an integration?

Many users have Spotcast installed...i thought Ha Team care about his users...

Seems not.

**Comment by fondberg** [comment] 2021-04-11 15:47
I understand them. I'm working on a solution which doesn't reguire a new HA. Hang in there and give them a break

**Comment by frenck** [comment] 2021-04-11 15:49
> Many users have Spotcast installed...i thought Ha Team care about their users...

Stop setting a scene. Just because the current offered solution isn't the right one for the core (which of course has the HA team priority), doesn't mean we don't help or don't care.

We've been talking with @fondberg on other approaches and solutions. This is how programming works. 1000's different solutions.

Let's be positive.

**Comment by frenck** [comment] 2021-04-11 15:50
> @frenck apologies, I wasn't aware of that distinction. But then, I'm just a user and shouldn't have to.

As a user, you definitely should know the difference. If you are using HACS, you have been warned multiple times.

**Comment by Electronlibre2012** [comment] 2021-04-11 16:13
> 
> 
> > Many users have Spotcast installed...i thought Ha Team care about their users...
> 
> Stop setting a scene. Just because the current offered solution isn't the right one for the core (which of course has the HA team priority), doesn't mean we don't help or don't care.
> 
> We've been talking with @fondberg on other approaches and solutions. This is how programming works. 1000's different solutions.
> 
> Let's be positive.

yes lets be positive, thanks,

i just dont understand : there is already Google Cast and Spotify,  why Spotcast can not be an official integration in HA in the futur?

**Comment by frenck** [comment] 2021-04-11 16:18
> why Spotcast can not be an official integration in HA in the future?

Spotcast uses an undocumented/unsupported feature of Spotify. While cool, it might cause problems for us, especially since Home Assistant hopes to get a dedicated application account with Spotify in the future.

**Comment by Electronlibre2012** [comment] 2021-04-11 16:25
ok understand. Sounds good...wait . Thanks for explanations.

**Comment by fondberg** [comment] 2021-04-11 17:04
Fixed in https://github.com/fondberg/spotcast/releases/tag/v3.5.2. Help me test that release.

**Closed by fondberg** 2021-04-11 17:04 UTC

**Comment by MagicMicky** [comment] 2021-04-11 17:17
I might be doing something wrong, but even on v3.5.2 it doesn't work for me.


```[140548344573040] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 264, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 375, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 392, in _async_run
    return await self.script.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1195, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 377, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 564, in getSpotifyDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not iterable
```

Script:
```
data:
  entity_id: media_player.Bedroom
  force_playback: true
service: spotcast.start
```

Also the Spotify Lovelace Card doesn't load anymore which might be unrelated

**Comment by ssiergl** [comment] 2021-04-11 17:22
Working without problems here. Getting all chromcast devices...can play and switch between the devices. Everything well again.

Thanks @fondberg and as well @frenck for the fix and the support

(supervised debian buster installation here)

**Comment by joselito11** [comment] 2021-04-11 17:34
Working, thank you!

**Comment by XalaTheShepard** [comment] 2021-04-11 17:34
Many thanks for the update. I tested it immediately out, but am sorry to inform you that it also does not work for me. The playlists keep on loading endlessly and the devices can not be found: 
![image](https://user-images.githubusercontent.com/69390987/114314914-f3580480-9afc-11eb-803a-35aff522717b.png)

**Comment by icarome** [comment] 2021-04-11 17:41
How did you update? It's working perfectly for me, even the spotify card. I've use the hacs release

**Comment by jghaanstra** [comment] 2021-04-11 17:42
Works for me as well, thanx @fondberg !

Cup of coffee coming your way.

**Comment by MagicMicky** [comment] 2021-04-11 17:58
Replying here on top of edit for visibility, and might help @XalaTheShepard 
I had errors from spotipy regarding credentials too.
After recreating an app on the Spotify Developer console (https://developer.spotify.com/dashboard/applications), reinstalling the spotify app and restarting things ended up working like before. Including the lovelace card.
Unsure about the root cause, but everything seems fine from Spotcast!

**Comment by roschi02** [comment] 2021-04-11 18:05
Don't forget to give him a coffee for his work!
[https://www.buymeacoffee.com/fondberg](https://www.buymeacoffee.com/fondberg)

**Comment by callebridholm** [comment] 2021-04-11 18:28
> I might be doing something wrong, but even on v3.5.2 it doesn't work for me.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
>     await handler.job.target(service_call)
>   File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 264, in service_handler
>     await script_entity.async_turn_on(
>   File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 375, in async_turn_on
>     await coro
>   File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 392, in _async_run
>     return await self.script.async_run(variables, context)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1195, in async_run
>     await asyncio.shield(run.async_run())
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
>     await self._async_step(log_exceptions=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
>     await service_task
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
>     await self._hass.async_add_executor_job(handler.job.target, service_call)
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/spotcast/__init__.py", line 377, in start_casting
>     spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
>   File "/config/custom_components/spotcast/__init__.py", line 564, in getSpotifyDeviceId
>     for device in devices_available["devices"]:
> TypeError: 'NoneType' object is not iterable
> ```
> 
> Script:
> 
> ```
> data:
>   entity_id: media_player.Bedroom
>   force_playback: true
> service: spotcast.start
> ```
> 
> Also the Spotify Lovelace Card doesn't load anymore which might be unrelated
> 
> Edit: looking more closely to my logs I also have a spotipy error `HTTP Error for GET to https://api.spotify.com/v1/me/ returned 401 due to The access token expired`; investigating
> 
> Edit 2: After reinstalling spotcast from scratch, reinstalling spotify integration, updating my sp_dc and sp_key credentials. It still wasn't working.
> After completely recreating an app on the Spotify Developer Console and updating the values for the Client ID and Secret ID (from the new app) for spotify this ended up working for me (including automations and spotify lovelace card). This seem unrelated and more an issue from the spotify integration? I'm still unsure why my previous developer app stopped working.

I have the exact same problem as you after upgrade of HA and this component

`2021-04-11 20:25:28 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 377, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 564, in getSpotifyDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not iterable
2021-04-11 20:25:28 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140379664766720] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 439, in handle_execute_script
    await script_obj.async_run(context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1195, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 341, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 377, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 564, in getSpotifyDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not iterable
`

**Comment by zhdenny** [comment] 2021-04-11 18:30
Update through HACS, restarted Home Assistant....and everything works. Good!

**Comment by Electronlibre2012** [comment] 2021-04-11 19:20
> 
> 
> Don't forget to give him a coffee for his work!
> https://www.buymeacoffee.com/fondberg

hope generosity and plenty of coffee cups for his nice and usefull Spotcast and card!

**Comment by mteuscher** [comment] 2021-04-11 19:34
HA via docker lastest release, updated through HACS, works like a charm! Thank you very much!

**Comment by walkercz** [comment] 2021-04-11 21:39
HA virtual box
core-2021.4.3
supervisor-2021.03.9
HACS - spotcast v3.5.2

I am newbie with spotcast - never run it successfully installed few days ago

tried to run it using mini media player or developer tools > services > 
spotcast.start

using service data:
        "entity_id" : "media_player.living_room",
	"uri" : "spotify:playlist:37i9dQZF1DX3yvAYDslnv8"

[140685081292080] 'NoneType' object is not iterable
[140685073151840] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 377, in start_casting
    spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
  File "/config/custom_components/spotcast/__init__.py", line 564, in getSpotifyDeviceId
    for device in devices_available["devices"]:
TypeError: 'NoneType' object is not iterable

**Comment by XalaTheShepard** [comment] 2021-04-11 21:40
Thanks everyone, working perfectly again. The spotify integration had to be reinstalled again. A good, well deserved cup of coffee is coming up :)

**Comment by lambdahindiii** [comment] 2021-04-11 21:51
It’s working great for me again too! I just updated via HACS and added the spotcast lines back into configuration.yaml and restarted. Everything working normally now (HA 2021.4.3 on HA OS on Raspberry Pi 4).

Thanks for all your hard work!

**Comment by pystha** [comment] 2021-04-11 22:51
HA 2021.4.3 in docker , Spotcast 3.5.2 it is not working anymore.
`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:323
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:50:47 AM (1 occurrences)
Last logged: 1:50:47 AM

[139970235530784] empty range for randrange() (0, 0, 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1519, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 390, in start_casting
    play(client, spotify_device_id, uri, random_song, repeat, shuffle, position)
  File "/config/custom_components/spotcast/__init__.py", line 323, in play
    position = random.randint(0, results["total"] - 1)
  File "/usr/local/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/usr/local/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, 0, 0)`

**Comment by johnjoemorgan** [comment] 2021-04-12 04:08
I had reverted to 2021.3.4 while waiting for this and another as yet to to worked out bug with Xiaomi Miio,

However, this morning saw the new HACS update for this and the requirement for 2021.4.x.  Being the contrarian I am I went ahead and updated with 2021.3.4 and I'm now typing this listening to spotify:artist:3BqAAo5E60L15TcFgWI8xH 

@fondberg and other ... many thanks.

**Comment by mcfly2283** [comment] 2021-04-12 05:06
Updated, but i got the same error than a few other "TypeError: 'NoneType' object is not iterable" when i want to start playback on Google-Device.

**Comment by fondberg** [comment] 2021-04-12 07:46
@walkercz ask in the forum. Seems like you haven't gotten the keys correctly

**Comment by callebridholm** [comment] 2021-04-12 08:49
> Updated, but i got the same error than a few other "TypeError: 'NoneType' object is not iterable" when i want to start playback on Google-Device.
> 
> EDIT: After readding Spotify Developer-Application and configuration of the Spotify-Integration evereything`s working. Thank you! :)

Do we need to have the Spotify integration also in Home Assistant to get this working? Thought that this component was the only one needed and that is how I used it for a long time. Can´t see any required step in the installation part of this plugin either. 
Tried to reinstall the plugin and get new sp_dc and sp_key without any luck, still same error

**Comment by mcfly2283** [comment] 2021-04-12 09:44
> > Updated, but i got the same error than a few other "TypeError: 'NoneType' object is not iterable" when i want to start playback on Google-Device.
> > EDIT: After readding Spotify Developer-Application and configuration of the Spotify-Integration evereything`s working. Thank you! :)
> 
> Do we need to have the Spotify integration also in Home Assistant to get this working? Thought that this component was the only one needed and that is how I used it for a long time. Can´t see any required step in the installation part of this plugin either.
> Tried to reinstall the plugin and get new sp_dc and sp_key without any luck, still same error

This is what i`ve found for the custom Spotify-Card:
"Spotify Integration and spotcast have to be installed (Spotcast is needed for many other things than playing on cast devices). This card should work in all newer major browsers. If it does not work for you please provide detailed reports in an issue ticket."
https://github.com/custom-cards/spotify-card

**Comment by callebridholm** [comment] 2021-04-12 18:17
> > > Updated, but i got the same error than a few other "TypeError: 'NoneType' object is not iterable" when i want to start playback on Google-Device.
> > > EDIT: After readding Spotify Developer-Application and configuration of the Spotify-Integration evereything`s working. Thank you! :)
> > 
> > 
> > Do we need to have the Spotify integration also in Home Assistant to get this working? Thought that this component was the only one needed and that is how I used it for a long time. Can´t see any required step in the installation part of this plugin either.
> > Tried to reinstall the plugin and get new sp_dc and sp_key without any luck, still same error
> 
> This is what i`ve found for the custom Spotify-Card:
> "Spotify Integration and spotcast have to be installed (Spotcast is needed for many other things than playing on cast devices). This card should work in all newer major browsers. If it does not work for you please provide detailed reports in an issue ticket."
> https://github.com/custom-cards/spotify-card

Added this Spotify integration now and it start working again, thanks for help
