### ISSUE TITLE
Spotcast stopped working

### ISSUE THREAD

**Issue by Gr3ytooth** [fondberg/spotcast#402] opened 2023-08-31 20:37 UTC
# Bug Ticket

## Describe the bug

I've had Spotcast working for a year or so and then about a week ago it stopped working. My memory a bit off, so not 100 % sure, but I don't think I've done anything special with my HA or anything related to network or Google Home. May have updated from HA 2023.8.1 to .3 or .4 but nothing else and definately not changing any configurations.

So from one day to another my automation that starts playlists on two of my Google Home speakers stopped playing the playlists. When I trigger my automation I can hear a ping from the speaker but nothing starts playing. Same behaviour consistently since then. Tried restarting HA multiple time but that makes no difference. I can see some error message in the HA log but it doesn't make sense to me.

Tonight I tried troubleshooting it but can't get it to work. So far I've tried
- Got new sp_key and sp_dc values for my config
- Uninstalling the official Spotify integration and spotcast and then reinstalling them
- Deleted the spotify app in the dev site and created a new one
- Got new sp_key and sp_dc values again. and again.

But it doesn't help. So reaching out here in hope for some tips. I need this awesome function!! :)

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [X] Using latest version of spotcast
* [X] Using latest stable version of Home Assistant
* [X] I have setup the Spotify integration in Home Assistant
* [X] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [X] (optional) I have Spotify Premium
* [X] (optional) I am using multiple accounts
* [X] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [X] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: Container
 - HA version: [2023.8.4]
 - spotcast version: [3.7.0]

## Configuration

spotcast:
  sp_dc: XXXX
  sp_key: yyy
  country: SE
  accounts:
    fredrik:
      sp_dc: ABC123
      sp_key: adsjkads
    theodor:
      sp_dc: XXXX (same as primary sp_dc)
      sp_key: yyy (same as primary sp_key)
    zacharias:
      sp_dc: asadsads
      sp_key: adsdasads

## Service Call

service: spotcast.start
data:
  device_name: "{{ states('sensor.media_device_choice') }}"
  entity_id: "{{ states('sensor.media_speaker_choice') }}"
  uri: "{{ states('sensor.media_playlist_choice') }}"
  account: "{{ states('sensor.media_user_choice') }}"
  random_song: true

## Logs

ERROR MESSAGE 1:
================

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Timeout when waiting for status response from Spotify app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2018, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/__init__.py", line 221, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 250, in get_spotify_device_id
    spotify_cast_device.startSpotifyController(access_token, expires)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 95, in startSpotifyController
    sp.launch_app()
  File "/config/custom_components/spotcast/spotify_controller.py", line 104, in launch_app
    raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app

ERROR MESSAGE 2
=================
Logger: pychromecast.socket_client
Source: custom_components/spotcast/spotify_controller.py:47
Integration: Spotcast ([documentation](https://github.com/fondberg/spotcast), [issues](https://github.com/fondberg/spotcast/issues))
First occurred: 21:41:24 (1 occurrences)
Last logged: 21:41:24

[(192.168.1.218):8009] Exception caught while sending message to controller SpotifyController: Message urn:x-cast:com.spotify.chromecast.secure.v1 from c79d5af9-79a3-4164-b4d6-8407af6e5cb1 to sender-0: {'type': 'getInfoResponse', 'payload': {'version': '2.9.0', 'publicKey': 'empty', 'remoteName': 'Spotify on Cast', 'deviceType': 'cast_audio', 'brandDisplayName': 'google', 'modelDisplayName': 'Google_Home', 'libraryVersion': '5.30.3', 'resolverVersion': '1', 'groupStatus': 'NONE', 'deviceAPI_isGroup': False, 'tokenType': 'accesstoken', 'clientID': 'd7df0887fb71494ea994202cb473eae7', 'productID': 0, 'scope': 'streaming', 'availability': '', 'spotifyError': 0, 'status': 101, 'statusString': 'OK'}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pychromecast/socket_client.py", line 719, in _route_message
    handled = handler.receive_message(message, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotify_controller.py", line 47, in receive_message
    self.device = data["payload"]["deviceID"]
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'deviceID'



HA LOG example:
==============
2023-08-31 19:41:23.295 DEBUG (SyncWorker_6) [custom_components.spotcast.helpers] get_cast_devices: media_player.zacharias_rum_speaker: None cast info: ChromecastInfo(cast_info=CastInfo(services={ServiceInfo(type='host', data=('192.168.1.181', 8009)), ServiceInfo(type='mdns', data='Google-Nest-Mini-8a572cc55275d5686c940d40baa096f0._googlecast._tcp.local.')}, uuid=UUID('8a572cc5-5275-d568-6c94-0d40baa096f0'), model_name='Google Nest Mini', friendly_name='Zacharias rum speaker', host='192.168.1.181', port=8009, cast_type='audio', manufacturer='Google Inc.'), is_dynamic_group=None)

**Comment by antonio1475** [comment] 2023-09-01 07:35
Duplicate of https://github.com/fondberg/spotcast/issues/398 ?

**Closed** 2023-09-01 09:55 UTC
Labels: bug
